package dl.gl1.GraphicsObjects;

public class Point4f {

    public float x;
    public float y;
    public float z;
    public float a;
    

    // default constructor
    // initialize four variables as 0
    public Point4f() {
	x = 0.0f;
	y = 0.0f;
	z = 0.0f;
	a = 0.0f;
    }

    public Point4f(float x,float y,float z) {
	this(x,y,z,0);
    }
    
    // initializing constructor
    /**
     * @param x the value of point's x-axis
     * 
     * @param y the value of point's y-axis
     * 
     * @param z the value of point's z-axis
     * 
     * @param a the value of point's a-axis
     */
    public Point4f(float x, float y, float z, float a) {
	this.x = x;
	this.y = y;
	this.z = z;
	this.a = a;
    }

    // sometimes for different algorithms we will need to address the point using
    // positions 0 1 2 3
    public float getPostion(int postion) {
	switch (postion) {
	case 0:
	    return x;
	case 1:
	    return y;
	case 2:
	    return z;
	case 3:
	    return a;
	default:
	    return Float.NaN;
	}
    }

    // @return convert the location of this point to the form of (x,y,z,a)
    public String toString() {
	return ("(" + x + "," + y + "," + z + "," + a + ")");
    }

    // @param the vector that this point will add
    // @return the position of the point add the specific vector
    public Point4f PlusVector(Vector4f Additonal) {
	return new Point4f(x + Additonal.x, y + Additonal.y, z + Additonal.z, a + Additonal.a);
    }

    // @param the vector that this point will minus
    // @return the position of the point minus the specific vector
    public Point4f MinusVector(Vector4f Minus) {
	return new Point4f(x - Minus.x, y - Minus.y, z - Minus.z, a - Minus.a);
    }

    // @param the point that this point will minus
    // @return the vector of the point minus the specific vector
    public Vector4f MinusPoint(Point4f Minus) {
	return new Vector4f(x - Minus.x, y - Minus.y, z - Minus.z, a - Minus.a);
    }

}

/*
 * .............................................................................
 * ...
 * .............................................................................
 * ...
 * .............................................................................
 * ...
 * .............................................................................
 * ...
 * .............................................................................
 * ...
 * .............................................................................
 * ...
 * .............................................................................
 * ...
 * .............................................................................
 * ...
 * .............................................................................
 * ...
 * ....................................=?7777+..................................
 * ...
 * .............................,8MMMMMMMMMMMMMMMMM7............................
 * ...
 * ...........................$MMMMMMMMMMMMMMMMMMMMMM7..........................
 * ...
 * ........................IMMMMMMMMMMMMMMMMMMMMMMMMMMMM?.......................
 * ...
 * ......................?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN.....................
 * ...
 * .....................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$...................
 * ...
 * ...................ZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM..................
 * ...
 * ..................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8.................
 * ...
 * .................NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM................
 * ...
 * ................IMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...............
 * ...
 * ................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$..............
 * ...
 * ...............=MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZ.............
 * ...
 * ..............:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.............
 * ...
 * ..............7MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:............
 * ...
 * ..............DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZ............
 * ... ..............MMMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMM8...............
 * ..............MMMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMN............... ..............NMMMMMMMMMMMMMMMMMMMM
 * MM MMMMMMMMMMMMMMMMMMMMMMMMMO...............
 * ..............$MMMMMMMMMMMMMMMMMM MMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMMI............... ..............+MMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMM=............... ...............8MMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMMM................
 * ................MMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMM8................
 * ................MMMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMMN,................
 * ................=MMMMMMMMMMMMMMMMMMMMM
 * MMMMMMMMMMMMMMMMMMMMMMM..................
 * .................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZ...............
 * ...
 * ..................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD................
 * ...
 * ...................?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM..................
 * ...
 * ....................8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...................
 * ...
 * .....................,8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM,....................
 * ...
 * ........................NMMMMMMMMMMMMMMMMMMMMMMMMMMMMN?......................
 * ...
 * ..........................NMMMMMMMMMMMMMMMMMMMMMMMMMI........................
 * ...
 * .............................$MMMMMMMMMMMMMMMMMMM?...........................
 * ...
 * .................................,I$NMMMMMN$?................................
 * ...
 * .............................................................................
 * ...
 * .............................................................................
 * ...
 * .............................................................................
 * ... .......................................................................
 */
